/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CheckOutPanel.java
 *
 * Created on 15-Apr-2011, 12:16:09 PM
 */

package ui;

/**
 *
 * @author cwang01
 */
public class CheckOutPanel extends javax.swing.JPanel {

    /** Creates new form CheckOutPanel */
    public CheckOutPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        outOkButton = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        transactionScrollPane = new javax.swing.JScrollPane();
        transactionTable = new javax.swing.JTable();
        outCustomerInfoPanel = new javax.swing.JPanel();
        outPhoneField = new javax.swing.JTextField();
        outNameLabel = new javax.swing.JLabel();
        outPhoneLabel = new javax.swing.JLabel();
        outPenalthField = new javax.swing.JTextField();
        outDLField = new javax.swing.JTextField();
        outNameField = new javax.swing.JTextField();
        outPenaltyLabel = new javax.swing.JLabel();
        outDLLabel = new javax.swing.JLabel();
        outLicenseLabel = new javax.swing.JLabel();
        outLicenseField = new javax.swing.JTextField();
        outCIdField = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        outCIdLabel = new javax.swing.JLabel();

        jLabel1.setText("$");

        jTextField3.setEditable(false);

        jTextField2.setText("jTextField2");

        jLabel6.setText("Total");

        jLabel5.setText("HST");

        jButton9.setText("Add Panelty");

        jButton3.setText("Reset");

        jButton11.setText("Check Out");

        jButton7.setText("ADD");

        outOkButton.setText("OK");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Discount", "Discount 1" }));

        jButton8.setText("DELETE");

        jButton2.setText("<-");

        transactionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {new Integer(25), "ET - DVD - Rental", new Integer(700)},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ib", "Description", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        transactionScrollPane.setViewportView(transactionTable);

        outCustomerInfoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        outPhoneField.setEditable(false);

        outNameLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        outNameLabel.setText("Name:");

        outPhoneLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        outPhoneLabel.setText("Phone Number:");

        outPenalthField.setEditable(false);
        outPenalthField.setText("$123");
        outPenalthField.setFocusable(false);

        outDLField.setEditable(false);
        outDLField.setFocusable(false);

        outNameField.setEditable(false);
        outNameField.setText("Customer Name");
        outNameField.setFocusable(false);

        outPenaltyLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        outPenaltyLabel.setText("Penalty:");

        outDLLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        outDLLabel.setText("Status:");

        outLicenseLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        outLicenseLabel.setText("Driver's License:");

        outLicenseField.setEditable(false);

        javax.swing.GroupLayout outCustomerInfoPanelLayout = new javax.swing.GroupLayout(outCustomerInfoPanel);
        outCustomerInfoPanel.setLayout(outCustomerInfoPanelLayout);
        outCustomerInfoPanelLayout.setHorizontalGroup(
            outCustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outCustomerInfoPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(outPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(outNameLabel)
                .addGap(5, 5, 5)
                .addComponent(outPhoneLabel)
                .addGap(5, 5, 5)
                .addComponent(outPenalthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(outDLField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(outNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(outPenaltyLabel)
                .addGap(5, 5, 5)
                .addComponent(outDLLabel)
                .addGap(5, 5, 5)
                .addComponent(outLicenseLabel)
                .addGap(5, 5, 5)
                .addComponent(outLicenseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        outCustomerInfoPanelLayout.setVerticalGroup(
            outCustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outCustomerInfoPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(outPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(outCustomerInfoPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(outNameLabel))
            .addGroup(outCustomerInfoPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(outPhoneLabel))
            .addGroup(outCustomerInfoPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(outPenalthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(outCustomerInfoPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(outDLField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(outCustomerInfoPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(outNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(outCustomerInfoPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(outPenaltyLabel))
            .addGroup(outCustomerInfoPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(outDLLabel))
            .addGroup(outCustomerInfoPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(outLicenseLabel))
            .addGroup(outCustomerInfoPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(outLicenseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        outCIdField.setText("123456");

        jTextField4.setEditable(false);
        jTextField4.setText("700");

        outCIdLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        outCIdLabel.setText("Customer ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(transactionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143)
                .addComponent(outCIdLabel)
                .addGap(5, 5, 5)
                .addComponent(outCIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(outOkButton)
                .addGap(5, 5, 5)
                .addComponent(jButton7))
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jButton8)
                .addGap(5, 5, 5)
                .addComponent(jButton9)
                .addGap(5, 5, 5)
                .addComponent(jLabel5)
                .addGap(5, 5, 5)
                .addComponent(jLabel6)
                .addGap(5, 5, 5)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(outCustomerInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jButton11)
                .addGap(5, 5, 5)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jButton2)
                .addGap(5, 5, 5)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jButton3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(outCIdLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(outCIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(outOkButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jButton7))
                    .addComponent(transactionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outCustomerInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jButton11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1))
                    .addComponent(jButton3)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField outCIdField;
    private javax.swing.JLabel outCIdLabel;
    private javax.swing.JPanel outCustomerInfoPanel;
    private javax.swing.JTextField outDLField;
    private javax.swing.JLabel outDLLabel;
    private javax.swing.JTextField outLicenseField;
    private javax.swing.JLabel outLicenseLabel;
    private javax.swing.JTextField outNameField;
    private javax.swing.JLabel outNameLabel;
    private javax.swing.JButton outOkButton;
    private javax.swing.JTextField outPenalthField;
    private javax.swing.JLabel outPenaltyLabel;
    private javax.swing.JTextField outPhoneField;
    private javax.swing.JLabel outPhoneLabel;
    private javax.swing.JScrollPane transactionScrollPane;
    private javax.swing.JTable transactionTable;
    // End of variables declaration//GEN-END:variables

}
