/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CustomerInfoDialog.java
 *
 * Created on 12-Apr-2011, 5:51:40 PM
 */

package ui;
import account.Customer;
import account.Address;
import account.AccountManagement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import pos.SQLhelper;
/**
 *
 * @author kpoirier00
 */
public class CustomerInfoDialog extends javax.swing.JDialog {
    private int panelType;

    /** Creates new form CustomerInfoDialog */
    public CustomerInfoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

        /** Creates new form CustomerInfoDialog */
    public CustomerInfoDialog(int panelType,boolean modal) {
        this.panelType = panelType;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleCustomerInfoLabel = new javax.swing.JLabel();
        postalCodeCustomerTextField = new javax.swing.JTextField();
        postalCodeCustomerLabel = new javax.swing.JLabel();
        countryCustomerTextField = new javax.swing.JTextField();
        provinceCustomerTextField = new javax.swing.JTextField();
        cityCustomerTextField = new javax.swing.JTextField();
        empIDCustomerTextField = new javax.swing.JTextField();
        countryCustomerLabel = new javax.swing.JLabel();
        okCustomerInfoButton = new javax.swing.JButton();
        provinceCustomerLabel = new javax.swing.JLabel();
        FirstNameCustomerTextField = new javax.swing.JTextField();
        cityCustomerLabel = new javax.swing.JLabel();
        houseNumberCustomerLabel = new javax.swing.JLabel();
        empIDCustomerLabel = new javax.swing.JLabel();
        streetNameCustomerLabel = new javax.swing.JLabel();
        penaltyCustomerLabel = new javax.swing.JLabel();
        streetNameCustomerTextField = new javax.swing.JTextField();
        fNameCustomerLabel = new javax.swing.JLabel();
        lNameCustomerLabel = new javax.swing.JLabel();
        lNameCustomerInfoTextfield = new javax.swing.JTextField();
        addressCustomerLabel = new javax.swing.JLabel();
        houseNumberCustomerTextField = new javax.swing.JTextField();
        penaltyCustomerTextField = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        DLCustInfoTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        enteredIntoDatabaseLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleCustomerInfoLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titleCustomerInfoLabel.setText("Customer Information");
        getContentPane().add(titleCustomerInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 11, -1, -1));

        postalCodeCustomerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postalCodeCustomerTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(postalCodeCustomerTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 260, -1));

        postalCodeCustomerLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        postalCodeCustomerLabel.setText("Postal Code");
        getContentPane().add(postalCodeCustomerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, -1, -1));
        getContentPane().add(countryCustomerTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 260, -1));
        getContentPane().add(provinceCustomerTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 52, -1));
        getContentPane().add(cityCustomerTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 200, -1));

        empIDCustomerTextField.setEditable(false);
        getContentPane().add(empIDCustomerTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 172, 260, -1));

        countryCustomerLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        countryCustomerLabel.setText("Country");
        getContentPane().add(countryCustomerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        okCustomerInfoButton.setText("OK");
        okCustomerInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okCustomerInfoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okCustomerInfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, -1, -1));

        provinceCustomerLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        provinceCustomerLabel.setText("Province");
        getContentPane().add(provinceCustomerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));
        getContentPane().add(FirstNameCustomerTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 78, 260, -1));

        cityCustomerLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cityCustomerLabel.setText("City");
        getContentPane().add(cityCustomerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        houseNumberCustomerLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        houseNumberCustomerLabel.setText("House #");
        getContentPane().add(houseNumberCustomerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        empIDCustomerLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        empIDCustomerLabel.setText("CustomerID:");
        getContentPane().add(empIDCustomerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 175, -1, -1));

        streetNameCustomerLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        streetNameCustomerLabel.setText("Street Name");
        getContentPane().add(streetNameCustomerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        penaltyCustomerLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        penaltyCustomerLabel.setText("Penalty:");
        getContentPane().add(penaltyCustomerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 229, -1, -1));
        getContentPane().add(streetNameCustomerTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 163, -1));

        fNameCustomerLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fNameCustomerLabel.setText("First Name:");
        getContentPane().add(fNameCustomerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 81, -1, -1));

        lNameCustomerLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lNameCustomerLabel.setText("Last Name:");
        getContentPane().add(lNameCustomerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, -1, -1));

        lNameCustomerInfoTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameCustomerInfoTextfieldActionPerformed(evt);
            }
        });
        getContentPane().add(lNameCustomerInfoTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 109, 260, -1));

        addressCustomerLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addressCustomerLabel.setText("Address:");
        getContentPane().add(addressCustomerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));
        getContentPane().add(houseNumberCustomerTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 91, -1));

        penaltyCustomerTextField.setEditable(false);
        getContentPane().add(penaltyCustomerTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 229, 260, -1));

        phoneLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        phoneLabel.setText("Phone Number:");
        getContentPane().add(phoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 144, -1, -1));

        phoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneFieldActionPerformed(evt);
            }
        });
        getContentPane().add(phoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 141, 260, -1));
        getContentPane().add(DLCustInfoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 203, 260, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Drivers License:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 206, 94, -1));

        enteredIntoDatabaseLabel1.setVisible(false);
        enteredIntoDatabaseLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        enteredIntoDatabaseLabel1.setForeground(new java.awt.Color(255, 51, 51));
        enteredIntoDatabaseLabel1.setText("CUSTOMER ENTERED INTO DATABASE");
        getContentPane().add(enteredIntoDatabaseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 46, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_phoneFieldActionPerformed

    private void lNameCustomerInfoTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameCustomerInfoTextfieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_lNameCustomerInfoTextfieldActionPerformed

    private void okCustomerInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okCustomerInfoButtonActionPerformed
        try {
            // TODO add your handling code here:
            addToDatabase();
        } catch (SQLException ex) {
            Logger.getLogger(CustomerInfoDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerInfoDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(CustomerInfoDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        CustomerInfoDialog dialog = new CustomerInfoDialog(new javax.swing.JFrame(), true);
        dialog.setVisible(false);
}//GEN-LAST:event_okCustomerInfoButtonActionPerformed

    private void postalCodeCustomerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postalCodeCustomerTextFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_postalCodeCustomerTextFieldActionPerformed

    private void addToDatabase() throws SQLException, ClassNotFoundException, Exception{
        AccountManagement populateData = new AccountManagement();
        String fname = FirstNameCustomerTextField.getText();
        String lname = lNameCustomerInfoTextfield.getText();
        String phoneNum = phoneField.getText();
        Integer houseNum = 0;
        try{
            houseNum = Integer.parseInt(houseNumberCustomerTextField.getText());
        } catch(NumberFormatException ex){
            enteredIntoDatabaseLabel1.setText("Please Fill All Fields");
            enteredIntoDatabaseLabel1.setVisible(true);
        }
        String streetName = streetNameCustomerTextField.getText();
        String city = cityCustomerTextField.getText();
        String province = provinceCustomerTextField.getText();
        String country = countryCustomerTextField.getText();
        String postalCode = postalCodeCustomerTextField.getText();
        String DLCustInfo = DLCustInfoTextField.getText();


        if (fname.equals("") || lname.equals("") || phoneNum.equals("") ||
            streetName.equals("") ||city.equals("") || province.equals("") || country.equals("") ||
            postalCode.equals("") || DLCustInfo.equals("")){
            enteredIntoDatabaseLabel1.setText("Please Fill All Fields");
            enteredIntoDatabaseLabel1.setVisible(true);
        }else{
            int customerID = populateData.generateNewID("customer");
            empIDCustomerTextField.setText("" + customerID);
            Address customerAddress = new Address(houseNum, streetName, city, province, country, postalCode);
            populateData.createCustomer(customerID, DLCustInfo, fname, lname, customerAddress, phoneNum);
            if (panelType == 1)
                    enteredIntoDatabaseLabel1.setText("CUSTOMER ENTERED INTO DATABASE");
            else enteredIntoDatabaseLabel1.setText("CUSTOMER HAS BEEN UPDATED");
            enteredIntoDatabaseLabel1.setVisible(true);

        }
    }
    /**
    * @param args the command line arguments
    */

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CustomerInfoDialog dialog = new CustomerInfoDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DLCustInfoTextField;
    private javax.swing.JTextField FirstNameCustomerTextField;
    private javax.swing.JLabel addressCustomerLabel;
    private javax.swing.JLabel cityCustomerLabel;
    private javax.swing.JTextField cityCustomerTextField;
    private javax.swing.JLabel countryCustomerLabel;
    private javax.swing.JTextField countryCustomerTextField;
    private javax.swing.JLabel empIDCustomerLabel;
    private javax.swing.JTextField empIDCustomerTextField;
    private javax.swing.JLabel enteredIntoDatabaseLabel1;
    private javax.swing.JLabel fNameCustomerLabel;
    private javax.swing.JLabel houseNumberCustomerLabel;
    private javax.swing.JTextField houseNumberCustomerTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField lNameCustomerInfoTextfield;
    private javax.swing.JLabel lNameCustomerLabel;
    private javax.swing.JButton okCustomerInfoButton;
    private javax.swing.JLabel penaltyCustomerLabel;
    private javax.swing.JTextField penaltyCustomerTextField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel postalCodeCustomerLabel;
    private javax.swing.JTextField postalCodeCustomerTextField;
    private javax.swing.JLabel provinceCustomerLabel;
    private javax.swing.JTextField provinceCustomerTextField;
    private javax.swing.JLabel streetNameCustomerLabel;
    private javax.swing.JTextField streetNameCustomerTextField;
    private javax.swing.JLabel titleCustomerInfoLabel;
    // End of variables declaration//GEN-END:variables

}
