/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CustomerInfoDialog.java
 *
 * Created on 12-Apr-2011, 5:51:40 PM
 */

package ui;
import account.Customer;
import account.Address;
import account.AccountManagement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import pos.SQLhelper;
/**
 *
 * @author kpoirier00
 */
public class CustomerInfoDialog extends javax.swing.JDialog {
    private int panelType;

    /** Creates new form CustomerInfoDialog */
    public CustomerInfoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

        /** Creates new form CustomerInfoDialog */
    public CustomerInfoDialog(int panelType,boolean modal) {
        this.panelType = panelType;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleCustomerInfoLabel = new javax.swing.JLabel();
        postalCodeCustomerTextField = new javax.swing.JTextField();
        postalCodeCustomerLabel = new javax.swing.JLabel();
        countryCustomerTextField = new javax.swing.JTextField();
        provinceCustomerTextField = new javax.swing.JTextField();
        cityCustomerTextField = new javax.swing.JTextField();
        empIDCustomerTextField = new javax.swing.JTextField();
        countryCustomerLabel = new javax.swing.JLabel();
        okCustomerInfoButton = new javax.swing.JButton();
        provinceCustomerLabel = new javax.swing.JLabel();
        FirstNameCustomerTextField = new javax.swing.JTextField();
        cityCustomerLabel = new javax.swing.JLabel();
        houseNumberCustomerLabel = new javax.swing.JLabel();
        empIDCustomerLabel = new javax.swing.JLabel();
        streetNameCustomerLabel = new javax.swing.JLabel();
        penaltyCustomerLabel = new javax.swing.JLabel();
        streetNameCustomerTextField = new javax.swing.JTextField();
        fNameCustomerLabel = new javax.swing.JLabel();
        lNameCustomerLabel = new javax.swing.JLabel();
        lNameCustomerInfoTextfield = new javax.swing.JTextField();
        addressCustomerLabel = new javax.swing.JLabel();
        houseNumberCustomerTextField = new javax.swing.JTextField();
        penaltyCustomerTextField = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        DLCustInfoTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        enteredIntoDatabaseLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleCustomerInfoLabel.setFont(new java.awt.Font("Tahoma", 0, 24));
        titleCustomerInfoLabel.setText("Customer Information");

        postalCodeCustomerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postalCodeCustomerTextFieldActionPerformed(evt);
            }
        });

        postalCodeCustomerLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        postalCodeCustomerLabel.setText("Postal Code");

        empIDCustomerTextField.setEditable(false);

        countryCustomerLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        countryCustomerLabel.setText("Country");

        okCustomerInfoButton.setText("OK");
        okCustomerInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okCustomerInfoButtonActionPerformed(evt);
            }
        });

        provinceCustomerLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        provinceCustomerLabel.setText("Province");

        cityCustomerLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        cityCustomerLabel.setText("City");

        houseNumberCustomerLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        houseNumberCustomerLabel.setText("House #");

        empIDCustomerLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        empIDCustomerLabel.setText("CustomerID:");

        streetNameCustomerLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        streetNameCustomerLabel.setText("Street Name");

        penaltyCustomerLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        penaltyCustomerLabel.setText("Penalty:");

        fNameCustomerLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        fNameCustomerLabel.setText("First Name:");

        lNameCustomerLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        lNameCustomerLabel.setText("Last Name:");

        lNameCustomerInfoTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameCustomerInfoTextfieldActionPerformed(evt);
            }
        });

        addressCustomerLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        addressCustomerLabel.setText("Address:");

        penaltyCustomerTextField.setEditable(false);

        phoneLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        phoneLabel.setText("Phone Number:");

        phoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Drivers License:");

        enteredIntoDatabaseLabel1.setVisible(false);
        enteredIntoDatabaseLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        enteredIntoDatabaseLabel1.setForeground(new java.awt.Color(255, 51, 51));
        enteredIntoDatabaseLabel1.setText("CUSTOMER ENTERED INTO DATABASE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(titleCustomerInfoLabel))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(enteredIntoDatabaseLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(fNameCustomerLabel)
                .addGap(73, 73, 73)
                .addComponent(FirstNameCustomerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lNameCustomerLabel)
                .addGap(74, 74, 74)
                .addComponent(lNameCustomerInfoTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(phoneLabel)
                .addGap(51, 51, 51)
                .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(empIDCustomerLabel)
                .addGap(65, 65, 65)
                .addComponent(empIDCustomerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(DLCustInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(penaltyCustomerLabel)
                .addGap(90, 90, 90)
                .addComponent(penaltyCustomerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(addressCustomerLabel)
                .addGap(101, 101, 101)
                .addComponent(houseNumberCustomerLabel)
                .addGap(63, 63, 63)
                .addComponent(streetNameCustomerLabel))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(streetNameCustomerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(houseNumberCustomerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(cityCustomerLabel)
                .addGap(128, 128, 128)
                .addComponent(provinceCustomerLabel))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(cityCustomerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(provinceCustomerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(countryCustomerLabel))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(countryCustomerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(postalCodeCustomerLabel))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(postalCodeCustomerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(okCustomerInfoButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(titleCustomerInfoLabel)
                .addGap(6, 6, 6)
                .addComponent(enteredIntoDatabaseLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(fNameCustomerLabel))
                    .addComponent(FirstNameCustomerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lNameCustomerLabel))
                    .addComponent(lNameCustomerInfoTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(phoneLabel))
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(empIDCustomerLabel))
                    .addComponent(empIDCustomerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(DLCustInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(penaltyCustomerLabel)
                    .addComponent(penaltyCustomerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressCustomerLabel)
                    .addComponent(houseNumberCustomerLabel)
                    .addComponent(streetNameCustomerLabel))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(streetNameCustomerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(houseNumberCustomerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cityCustomerLabel)
                    .addComponent(provinceCustomerLabel))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cityCustomerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(provinceCustomerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(countryCustomerLabel)
                .addGap(6, 6, 6)
                .addComponent(countryCustomerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(postalCodeCustomerLabel)
                .addGap(6, 6, 6)
                .addComponent(postalCodeCustomerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(okCustomerInfoButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_phoneFieldActionPerformed

    private void lNameCustomerInfoTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameCustomerInfoTextfieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_lNameCustomerInfoTextfieldActionPerformed

    private void okCustomerInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okCustomerInfoButtonActionPerformed
        try {
            // TODO add your handling code here:
            addToDatabase();
        } catch (SQLException ex) {
            Logger.getLogger(CustomerInfoDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerInfoDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(CustomerInfoDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        CustomerInfoDialog dialog = new CustomerInfoDialog(new javax.swing.JFrame(), true);
        dialog.setVisible(false);
}//GEN-LAST:event_okCustomerInfoButtonActionPerformed

    private void postalCodeCustomerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postalCodeCustomerTextFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_postalCodeCustomerTextFieldActionPerformed

    private void addToDatabase() throws SQLException, ClassNotFoundException, Exception{
        AccountManagement populateData = new AccountManagement();
        String fname = FirstNameCustomerTextField.getText();
        String lname = lNameCustomerInfoTextfield.getText();
        String phoneNum = phoneField.getText();
        Integer houseNum = 0;
        try{
            houseNum = Integer.parseInt(houseNumberCustomerTextField.getText());
        } catch(NumberFormatException ex){
            enteredIntoDatabaseLabel1.setText("Please Fill All Fields");
            enteredIntoDatabaseLabel1.setVisible(true);
        }
        String streetName = streetNameCustomerTextField.getText();
        String city = cityCustomerTextField.getText();
        String province = provinceCustomerTextField.getText();
        String country = countryCustomerTextField.getText();
        String postalCode = postalCodeCustomerTextField.getText();
        String DLCustInfo = DLCustInfoTextField.getText();


        if (fname.equals("") || lname.equals("") || phoneNum.equals("") ||
            streetName.equals("") ||city.equals("") || province.equals("") || country.equals("") ||
            postalCode.equals("") || DLCustInfo.equals("")){
            enteredIntoDatabaseLabel1.setText("Please Fill All Fields");
            enteredIntoDatabaseLabel1.setVisible(true);
        }else{
            int customerID = populateData.generateNewID("customer");
            empIDCustomerTextField.setText("" + customerID);
            Address customerAddress = new Address(houseNum, streetName, city, province, country, postalCode);
            populateData.createCustomer(customerID, DLCustInfo, fname, lname, customerAddress, phoneNum);
            if (panelType == 1)
                    enteredIntoDatabaseLabel1.setText("CUSTOMER ENTERED INTO DATABASE");
            else enteredIntoDatabaseLabel1.setText("CUSTOMER HAS BEEN UPDATED");
            enteredIntoDatabaseLabel1.setVisible(true);

        }
    }
    /**
    * @param args the command line arguments
    */

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CustomerInfoDialog dialog = new CustomerInfoDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DLCustInfoTextField;
    private javax.swing.JTextField FirstNameCustomerTextField;
    private javax.swing.JLabel addressCustomerLabel;
    private javax.swing.JLabel cityCustomerLabel;
    private javax.swing.JTextField cityCustomerTextField;
    private javax.swing.JLabel countryCustomerLabel;
    private javax.swing.JTextField countryCustomerTextField;
    private javax.swing.JLabel empIDCustomerLabel;
    private javax.swing.JTextField empIDCustomerTextField;
    private javax.swing.JLabel enteredIntoDatabaseLabel1;
    private javax.swing.JLabel fNameCustomerLabel;
    private javax.swing.JLabel houseNumberCustomerLabel;
    private javax.swing.JTextField houseNumberCustomerTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField lNameCustomerInfoTextfield;
    private javax.swing.JLabel lNameCustomerLabel;
    private javax.swing.JButton okCustomerInfoButton;
    private javax.swing.JLabel penaltyCustomerLabel;
    private javax.swing.JTextField penaltyCustomerTextField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel postalCodeCustomerLabel;
    private javax.swing.JTextField postalCodeCustomerTextField;
    private javax.swing.JLabel provinceCustomerLabel;
    private javax.swing.JTextField provinceCustomerTextField;
    private javax.swing.JLabel streetNameCustomerLabel;
    private javax.swing.JTextField streetNameCustomerTextField;
    private javax.swing.JLabel titleCustomerInfoLabel;
    // End of variables declaration//GEN-END:variables

}
