/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EmployeeInfoDialog.java
 *
 * Created on 12-Apr-2011, 4:06:02 PM
 */
package ui;
import account.Customer;
import account.Address;
import account.AccountManagement;
import account.Employee;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import search.Search;



/**
 *
 * @author kpoirier00
 */
public class EmployeeInfoDialog extends javax.swing.JDialog {

    private String EmployeeID;
    private int panelType;
    private Employee currentEmployee;
    /** Creates new form EmployeeInfoDialog */
         /** Creates new form CustomerInfoDialog */

    public EmployeeInfoDialog(int panelType, boolean modal) {
        this.panelType = panelType;
        initComponents();
    }
    //EmployeeInfoDialog foo = new EmployeeInfoDialog(new javax.swing.JFrame(), true);

    public EmployeeInfoDialog(String EmployeeID, int panelType, boolean modal) {
        this.panelType = panelType;
        this.EmployeeID = EmployeeID;
        initComponents();
        PopulateFields(this.EmployeeID);
    }


    private void PopulateFields(String EmployeeID){
        try {
            Search employeeObject = new Search();
            currentEmployee = Search.getEmployee(Integer.parseInt(EmployeeID));
            System.out.println("employee Retrieved");
            System.out.println("return: " + currentEmployee.getFname());
            firstNameEmployeeInfoTextField.setText(currentEmployee.getFname());
            //System.out.println(currentEmployee.getFname());
            lastNameEmployeeInfoTextField.setText(currentEmployee.getLname());
            positionEmployeeInfoComboBox.setSelectedItem(currentEmployee.getPosition());
            phoneField.setText(currentEmployee.getPhoneNum());
            employeeIDEmployeeInfoTextField.setText("" + currentEmployee.getEmployeeID());
            Address address = currentEmployee.getAddress();
            houseNumberEmployeeInfoTextField.setText("" + address.getHouseNumber());
            streetNameEmployeeInfoTextField.setText(address.getStreetName());
            cityEmployeeInfoTextField.setText(address.getCity());
            provinceEmployeeInfoTextField.setText(address.getProvince());
            countryEmployeeInfoTextField.setText(address.getCountry());
            postalCodeEmployeeInfoTextField.setText(address.getPostalCode());
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeInfoDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EmployeeInfoDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

     private void addToDatabase(){
        try {
            AccountManagement populateData = new AccountManagement();

            String fname = firstNameEmployeeInfoTextField.getText();
            String lname = lastNameEmployeeInfoTextField.getText();
            String position = "" + positionEmployeeInfoComboBox.getSelectedItem();
            String phoneNum = phoneField.getText();
            Integer houseNum = 0;
            try {
                houseNum = Integer.parseInt(houseNumberEmployeeInfoTextField.getText());
            } catch (NumberFormatException ex) {
                enteredIntoDatabaseLabel1.setText("Please Fill All Fields");
                enteredIntoDatabaseLabel1.setVisible(true);
            }
            String streetName = streetNameEmployeeInfoTextField.getText();
            String city = cityEmployeeInfoTextField.getText();
            String province = provinceEmployeeInfoTextField.getText();
            String country = countryEmployeeInfoTextField.getText();
            String postalCode = postalCodeEmployeeInfoTextField.getText();

            if (fname.equals("") || lname.equals("") || phoneNum.equals("") || streetName.equals("") || city.equals("") || province.equals("") || country.equals("") || postalCode.equals("")) {
                enteredIntoDatabaseLabel1.setText("Please Fill All Fields");
                enteredIntoDatabaseLabel1.setVisible(true);
            } else {
                int employeeID;
                if(employeeIDEmployeeInfoTextField.getText().equals(""))
                    employeeID = populateData.generateNewID("employee");
                else employeeID = Integer.parseInt(employeeIDEmployeeInfoTextField.getText());
                employeeIDEmployeeInfoTextField.setText("" + employeeID);
                Address employeeAddress = new Address(houseNum, streetName, city, province, country, postalCode);
                
                if (panelType == 1){
                    enteredIntoDatabaseLabel1.setText("EMPLOYEE ENTERED INTO DATABASE");
                    populateData.createEmployee(employeeID,position, fname, lname, employeeAddress, phoneNum);
                }
                else if (panelType == 0){
                    enteredIntoDatabaseLabel1.setText("EMPLOYEE HAS BEEN UPDATED");
                    currentEmployee = new Employee(position, employeeID, fname, lname, employeeAddress, phoneNum);
                    AccountManagement.editPersonalInfo(currentEmployee);
                }
                enteredIntoDatabaseLabel1.setVisible(true);
            }

        } catch (SQLException ex) {
            Logger.getLogger(EmployeeInfoDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EmployeeInfoDialog.class.getName()).log(Level.SEVERE, null, ex);
        }catch (Exception ex) {
            Logger.getLogger(EmployeeInfoDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleEmployeeInfoLabel = new javax.swing.JLabel();
        employeeInfoButton = new javax.swing.JButton();
        firstNameEmployeeInfoTextField = new javax.swing.JTextField();
        employeeIDEmployeeInfoTextField = new javax.swing.JTextField();
        firstNameEmployeeInfoLabel = new javax.swing.JLabel();
        empIDEmployeeInfoLabel = new javax.swing.JLabel();
        positionEmployeeInfoLabel = new javax.swing.JLabel();
        houseNumberEmployeeInfoTextField = new javax.swing.JTextField();
        addressEmployeeInfoLabel = new javax.swing.JLabel();
        lastNameEmployeeInfoTextField = new javax.swing.JTextField();
        lastNameEmployeeInfoLabel = new javax.swing.JLabel();
        positionEmployeeInfoComboBox = new javax.swing.JComboBox();
        houseNumberEmployeeInfoLabel = new javax.swing.JLabel();
        streetNameEmployeeInfoTextField = new javax.swing.JTextField();
        streetNameEmployeeInfoLabel = new javax.swing.JLabel();
        cityEmployeeInfoLabel = new javax.swing.JLabel();
        provinceEmployeeInfoLabel = new javax.swing.JLabel();
        countryEmployeeInfoLabel = new javax.swing.JLabel();
        cityEmployeeInfoTextField = new javax.swing.JTextField();
        provinceEmployeeInfoTextField = new javax.swing.JTextField();
        countryEmployeeInfoTextField = new javax.swing.JTextField();
        postalCodeEmployeeInfoLabel = new javax.swing.JLabel();
        postalCodeEmployeeInfoTextField = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        enteredIntoDatabaseLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleEmployeeInfoLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titleEmployeeInfoLabel.setText("Employee Information");

        employeeInfoButton.setText("OK");
        employeeInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeInfoButtonActionPerformed(evt);
            }
        });

        employeeIDEmployeeInfoTextField.setEditable(false);

        firstNameEmployeeInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        firstNameEmployeeInfoLabel.setText("First Name:");

        empIDEmployeeInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        empIDEmployeeInfoLabel.setText("EmployeeID:");

        positionEmployeeInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        positionEmployeeInfoLabel.setText("Position:");

        addressEmployeeInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addressEmployeeInfoLabel.setText("Address:");

        lastNameEmployeeInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lastNameEmployeeInfoLabel.setText("Last Name:");

        positionEmployeeInfoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manager", "Employee" }));

        houseNumberEmployeeInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        houseNumberEmployeeInfoLabel.setText("House #");

        streetNameEmployeeInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        streetNameEmployeeInfoLabel.setText("Street Name");

        cityEmployeeInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        cityEmployeeInfoLabel.setText("City");

        provinceEmployeeInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        provinceEmployeeInfoLabel.setText("Province");

        countryEmployeeInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        countryEmployeeInfoLabel.setText("Country");

        postalCodeEmployeeInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        postalCodeEmployeeInfoLabel.setText("Postal Code");

        postalCodeEmployeeInfoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postalCodeEmployeeInfoTextFieldActionPerformed(evt);
            }
        });

        phoneLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        phoneLabel.setText("Phone Number:");

        phoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneFieldActionPerformed(evt);
            }
        });

        enteredIntoDatabaseLabel1.setVisible(false);
        enteredIntoDatabaseLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        enteredIntoDatabaseLabel1.setForeground(new java.awt.Color(255, 51, 51));
        enteredIntoDatabaseLabel1.setText("EMPLOYEE ENTERED IN DATABASE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(employeeInfoButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(positionEmployeeInfoLabel)
                                .addGap(104, 104, 104)
                                .addComponent(positionEmployeeInfoComboBox, 0, 253, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(empIDEmployeeInfoLabel)
                                .addGap(81, 81, 81)
                                .addComponent(employeeIDEmployeeInfoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(firstNameEmployeeInfoLabel)
                                .addGap(89, 89, 89)
                                .addComponent(firstNameEmployeeInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastNameEmployeeInfoLabel)
                                    .addComponent(phoneLabel))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phoneField, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                                    .addComponent(lastNameEmployeeInfoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addressEmployeeInfoLabel)
                                .addGap(103, 103, 103)
                                .addComponent(houseNumberEmployeeInfoLabel)
                                .addGap(18, 18, 18)
                                .addComponent(streetNameEmployeeInfoLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(houseNumberEmployeeInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(streetNameEmployeeInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(cityEmployeeInfoLabel)
                                .addGap(86, 86, 86)
                                .addComponent(provinceEmployeeInfoLabel)
                                .addGap(32, 32, 32)
                                .addComponent(countryEmployeeInfoLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(cityEmployeeInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(provinceEmployeeInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(countryEmployeeInfoTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(postalCodeEmployeeInfoLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(postalCodeEmployeeInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(titleEmployeeInfoLabel)))
                .addGap(91, 91, 91))
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(enteredIntoDatabaseLabel1)
                .addContainerGap(187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleEmployeeInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enteredIntoDatabaseLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(firstNameEmployeeInfoLabel))
                    .addComponent(firstNameEmployeeInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lastNameEmployeeInfoLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lastNameEmployeeInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(phoneLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(empIDEmployeeInfoLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(employeeIDEmployeeInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(positionEmployeeInfoLabel)
                    .addComponent(positionEmployeeInfoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(houseNumberEmployeeInfoLabel)
                        .addComponent(addressEmployeeInfoLabel))
                    .addComponent(streetNameEmployeeInfoLabel))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(houseNumberEmployeeInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(streetNameEmployeeInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cityEmployeeInfoLabel)
                    .addComponent(provinceEmployeeInfoLabel)
                    .addComponent(countryEmployeeInfoLabel))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cityEmployeeInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(provinceEmployeeInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(postalCodeEmployeeInfoLabel))
                    .addComponent(countryEmployeeInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(postalCodeEmployeeInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(employeeInfoButton)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void postalCodeEmployeeInfoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postalCodeEmployeeInfoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postalCodeEmployeeInfoTextFieldActionPerformed

    private void phoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_phoneFieldActionPerformed

    private void employeeInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeInfoButtonActionPerformed
        // TODO add your handling code here:
            addToDatabase();

    }//GEN-LAST:event_employeeInfoButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EmployeeInfoDialog dialog = new EmployeeInfoDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressEmployeeInfoLabel;
    private javax.swing.JLabel cityEmployeeInfoLabel;
    private javax.swing.JTextField cityEmployeeInfoTextField;
    private javax.swing.JLabel countryEmployeeInfoLabel;
    private javax.swing.JTextField countryEmployeeInfoTextField;
    private javax.swing.JLabel empIDEmployeeInfoLabel;
    private javax.swing.JTextField employeeIDEmployeeInfoTextField;
    private javax.swing.JButton employeeInfoButton;
    private javax.swing.JLabel enteredIntoDatabaseLabel1;
    private javax.swing.JLabel firstNameEmployeeInfoLabel;
    private javax.swing.JTextField firstNameEmployeeInfoTextField;
    private javax.swing.JLabel houseNumberEmployeeInfoLabel;
    private javax.swing.JTextField houseNumberEmployeeInfoTextField;
    private javax.swing.JLabel lastNameEmployeeInfoLabel;
    private javax.swing.JTextField lastNameEmployeeInfoTextField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JComboBox positionEmployeeInfoComboBox;
    private javax.swing.JLabel positionEmployeeInfoLabel;
    private javax.swing.JLabel postalCodeEmployeeInfoLabel;
    private javax.swing.JTextField postalCodeEmployeeInfoTextField;
    private javax.swing.JLabel provinceEmployeeInfoLabel;
    private javax.swing.JTextField provinceEmployeeInfoTextField;
    private javax.swing.JLabel streetNameEmployeeInfoLabel;
    private javax.swing.JTextField streetNameEmployeeInfoTextField;
    private javax.swing.JLabel titleEmployeeInfoLabel;
    // End of variables declaration//GEN-END:variables

}
