/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InventoryPanel.java
 *
 * Created on 15-Apr-2011, 1:05:52 PM
 */

package ui;

import account.Employee;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import search.Search;


/**
 *
 * @author cwang01
 */
public class EmployeePanel extends javax.swing.JPanel {


    //
    private ArrayList<Employee> employeeInfoObj;
    private Vector<Vector<String>> et_data; //used for data from database
    private Vector<String> et_header; //used to store data header


    /** Creates new form InventoryPanel */
    public EmployeePanel() {
        try {
            //get data from database
            employeeInfoObj = Search.getAllEmployees();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EmployeePanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(EmployeePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("size:  "+employeeInfoObj.size());
        et_data = new Vector<Vector<String>>();
        Vector<String> row = new Vector<String>();
        for(int i = 0; i < employeeInfoObj.size(); i++){
           Employee oneEmployee = (Employee)employeeInfoObj.get(i);

               row.add("" + oneEmployee.getFname() + " " + oneEmployee.getLname());
               row.add("" + oneEmployee.getPosition());
               et_data.add(row);
        }


         //create header for the table
        et_header = new Vector<String>();
        et_header.add("Name");
        et_header.add("Position");

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empScrollPane = new javax.swing.JScrollPane();
        empTable = new javax.swing.JTable(
            new javax.swing.table.DefaultTableModel(et_data, et_header));
        empPromoteButton = new javax.swing.JButton();
        empDemoteButton = new javax.swing.JButton();
        empAddButton = new javax.swing.JButton();
        empRemoveButton = new javax.swing.JButton();

        empScrollPane.setViewportView(empTable);

        empPromoteButton.setText("Promote");

        empDemoteButton.setText("Demote");

        empAddButton.setText("Add");

        empRemoveButton.setText("Remove");
        empRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empRemoveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(empScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(empDemoteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(empPromoteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(empRemoveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(empAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(empScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(empAddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(empRemoveButton)
                        .addGap(5, 5, 5)
                        .addComponent(empPromoteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(empDemoteButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void empRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empRemoveButtonActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_empRemoveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton empAddButton;
    private javax.swing.JButton empDemoteButton;
    private javax.swing.JButton empPromoteButton;
    private javax.swing.JButton empRemoveButton;
    private javax.swing.JScrollPane empScrollPane;
    private javax.swing.JTable empTable;
    // End of variables declaration//GEN-END:variables

}
