/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainJFrame.java
 *
 * Created on 8-Jul-2011, 10:29:16 AM
 */

//package UI2;

/**
 *
 * @author alby
 */
public class MainJFrame extends javax.swing.JFrame {

    /** Creates new form MainJFrame */
    public MainJFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 800));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        checkInPanel = new CheckInJPanel();
        jTabbedPane1.addTab("Check In", checkInPanel);
        checkOutPanel = new CheckOutJPanel();
        jTabbedPane1.addTab("Check Out", checkOutPanel);
        //membershipPanel = new ui.MembershipPanel();
        //jTabbedPane1.addTab("Membership", membershipPanel);
        inventoryPanel = new InventoryJPanel();
        jTabbedPane1.addTab("Inventory", inventoryPanel);
        employeePanel = new EmployeePanel();
        jTabbedPane1.addTab("Employee", employeePanel);
        //pricePanel = new ui.PriceSchemePanel();
        //jTabbedPane1.addTab("Price Scheme", pricePanel);
        //othersPanel = new ui.OthersPanel();
        //jTabbedPane1.addTab("Others", othersPanel);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private CheckInJPanel checkInPanel;
    private CheckOutJPanel checkOutPanel;
    //private ui.MembershipPanel membershipPanel;
    private InventoryJPanel inventoryPanel;
    private EmployeePanel employeePanel;
    //private ui.PriceSchemePanel pricePanel;
    //private OthersPanel othersPanel;
    // End of variables declaration//GEN-END:variables

}
