/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MembershipPanel.java
 *
 * Created on 15-Apr-2011, 1:05:28 PM
 */
package ui;
import account.Employee;
import account.Customer;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import search.Search;





 /*
 * @author cwang01
 */
public class MembershipPanel extends javax.swing.JPanel {
private Vector <Vector <String>> tableContent;
private Vector <String> header;

/**
    /** Creates new form MembershipPanel */
    public MembershipPanel() {
        MakeTable();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private Vector ReturnVector(ArrayList list){
        return new Vector(list);
    }

    private void MakeTable(){

      tableContent = new Vector<Vector <String>>();
      for(int i = 0; i < 1; i++){
          System.out.println("i = " + i);
          Vector temp = new Vector <String>();
          temp.add(" ");
          temp.add(" ");
          temp.add(" ");
          temp.add(" ");
          temp.add(" ");
          tableContent.add(temp);
      }

      header = new Vector<String>();
      header.add("Customer ID"); //Empid
      header.add("Name"); // employee name
      header.add("Phone Number"); // employee position
      header.add("Address"); // employee department
    }

    private void UpdateTable() {

      String searchItem = (String)inCIdField1.getText();
      String selectedItem = (String)jComboBox3.getSelectedItem();
      System.out.println("SearchItem: " + searchItem);
      tableContent = new Vector<Vector <String>>();
        DefaultTableModel table = (DefaultTableModel)jTable4.getModel();
        while (table.getRowCount()>0)
            table.removeRow(0);

        try {
            System.out.println("testestetsetset");
            ArrayList<account.Customer> result = Search.searchCustomers(searchItem, selectedItem);
            System.out.println("result mofo: " + result.size());
            if(result != null){
                for (int i = 0; i < result.size();i++) //inventory.GeneralMovie movie : result)
                {
                    account.Customer singleCustomer = (account.Customer)result.get(i);
                    System.out.println("result Size: " + singleCustomer.getDL());

                    Vector <String> row = new Vector<String>();
                    row.add("" + singleCustomer.getAccountID());
                    row.add("" + singleCustomer.getFname() + " " + singleCustomer.getLname());
                    row.add("" + singleCustomer.getPhoneNum());
                    row.add("" + singleCustomer.getAddress());
                    table.addRow(row);
                }
            }
            else{
                notFoundLabel.setVisible(true);
            }


        } catch (SQLException ex) {
            Logger.getLogger(CustomerFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException ex){
            inCIdField1.setText("Enter Value here:");
        } catch (NullPointerException ex){
            notFoundLabel.setVisible(true);
        } catch (Exception ex)
            {System.out.print(ex.getMessage());ex.printStackTrace();
        }
        table.fireTableStructureChanged();

    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        inCIdField1 = new javax.swing.JTextField();
        inCIdLabel1 = new javax.swing.JLabel();
        inCOkButton1 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox();
        jButton13 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        notFoundLabel = new javax.swing.JLabel();
        notFoundLabel.setVisible(false);

        setOpaque(false);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            tableContent,header
        ));
        jScrollPane5.setViewportView(jTable4);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        inCIdField1.setText("12345");

        inCIdLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        inCIdLabel1.setText("Customer:");

        inCOkButton1.setText("OK");
        inCOkButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inCOkButton1ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "Last Name", "Phone Number" }));

        jButton13.setText("Remove");

        jButton2.setText("Modify");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        notFoundLabel.setFont(new java.awt.Font("Tahoma", 1, 14));
        notFoundLabel.setForeground(new java.awt.Color(255, 102, 102));
        notFoundLabel.setText("Customer Not Found");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inCIdLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(inCIdField1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inCOkButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(notFoundLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inCOkButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(notFoundLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inCIdLabel1)
                        .addComponent(inCIdField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inCOkButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inCOkButton1ActionPerformed
        // TODO add your handling code here:
        UpdateTable();
    }//GEN-LAST:event_inCOkButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new CustomerInfoDialog(1,false).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new CustomerInfoDialog(2,false).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inCIdField1;
    private javax.swing.JLabel inCIdLabel1;
    private javax.swing.JButton inCOkButton1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel notFoundLabel;
    // End of variables declaration//GEN-END:variables

}
