/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OthersPanel.java
 *
 * Created on 15-Apr-2011, 1:06:42 PM
 */

package ui;

import javax.swing.filechooser.FileNameExtensionFilter;
import java.util.GregorianCalendar;
import java.sql.SQLException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Vector;
import inventory.*;
import javax.swing.table.DefaultTableModel;
import reports.*;

/**
 *
 * @author cwang01
 */
public class OthersPanel extends javax.swing.JPanel {

    private DefaultTableModel table;
    /** Creates new form OthersPanel */
    public OthersPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        reportPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        reportPanel = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Requested Move list", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jButton7.setText("View Requests");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAllRequests(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SKU", "Customer ID", "Request Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton8.setText("Remove a Request");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeRequest(evt);
            }
        });

        jButton9.setText("Clear All Request");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllRequest(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                            .addComponent(jButton7)
                            .addGap(152, 152, 152))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9)
                        .addContainerGap())))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        reportPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Import Movie From a File", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jTextField1.setEnabled(false);

        jLabel1.setText("Source Location");

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseCSVFile(evt);
            }
        });

        jButton2.setText("Import");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSVImport(evt);
            }
        });

        javax.swing.GroupLayout reportPanel1Layout = new javax.swing.GroupLayout(reportPanel1);
        reportPanel1.setLayout(reportPanel1Layout);
        reportPanel1Layout.setHorizontalGroup(
            reportPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(reportPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(reportPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        reportPanel1Layout.setVerticalGroup(
            reportPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reportPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addContainerGap())
        );

        reportPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sale Reports", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jTextField2.setEnabled(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Destination Location");

        jButton3.setText("Browse");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseReportDestination(evt);
            }
        });

        jButton4.setText("Daily Sale Report");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateDailyReport(evt);
            }
        });

        jButton5.setText("Monthly Sale Report");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateMonthlyReport(evt);
            }
        });

        jButton6.setText("Annualy Sale Report");
        jButton6.setActionCommand("Annual Sale Report");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateAnnualReport(evt);
            }
        });

        jLabel3.setText("Note: Genreating sale report may take some time.");

        javax.swing.GroupLayout reportPanelLayout = new javax.swing.GroupLayout(reportPanel);
        reportPanel.setLayout(reportPanelLayout);
        reportPanelLayout.setHorizontalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap())
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );
        reportPanelLayout.setVerticalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(17, 17, 17)
                .addComponent(jButton6)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reportPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reportPanel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(reportPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        reportPanel1.getAccessibleContext().setAccessibleName("Input Movie From a File");
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void ChooseCSVFile(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseCSVFile
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
        javax.swing.filechooser.FileNameExtensionFilter filter = new FileNameExtensionFilter("csv File", "csv");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(jButton1);
        if(returnVal == javax.swing.JFileChooser.APPROVE_OPTION)
            jTextField1.setText(chooser.getSelectedFile().getAbsolutePath());
    }//GEN-LAST:event_ChooseCSVFile

    private void CSVImport(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSVImport
        String path = jTextField1.getText();
        try
        {
            MovieManagement.createGeneralMovie(path);
            //ProgressBarForm here
            javax.swing.JOptionPane.showMessageDialog(this, "Import Movie Sucessful.",
                    "Import Movie From csv File", 1);
        }
        catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(),
                                                "Import Movie From csv File", 0);
        }
    }//GEN-LAST:event_CSVImport

    private void ChooseReportDestination(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseReportDestination
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
        javax.swing.filechooser.FileNameExtensionFilter filter = new FileNameExtensionFilter("txt file", "txt");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(jButton3);
        if(returnVal == javax.swing.JFileChooser.APPROVE_OPTION)
            jTextField2.setText(chooser.getSelectedFile().getAbsolutePath());
    }//GEN-LAST:event_ChooseReportDestination

    private void generateDailyReport(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateDailyReport
        GregorianCalendar today = new GregorianCalendar();
        String path = jTextField2.getText();
        try
        {
            SaleReporter reporter = new SaleReporter();
            reporter.generateReport(today, today, path);
            javax.swing.JOptionPane.showMessageDialog(this, "Sale report successfully" +
                    " generated", "Successful", 1);
        }
        catch(SQLException e)
        {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Database Error.", 0);
        }
        catch(IOException e)
        {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Destination path is bad.", 0);
        }
        catch(ClassNotFoundException e)
        {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Database Driver Problem", 0);
        }
    }//GEN-LAST:event_generateDailyReport

    private void getAllRequests(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAllRequests
        try
        {
            MovieManagement movieMan = new MovieManagement();
            Vector<String> cols = new Vector<String>();
            cols.add("SKU");
            cols.add("Customer ID");
            cols.add("Request Date");
            ArrayList<MovieRequest> allRequests = movieMan.getRequest();
            Vector<Vector<String>> data = new Vector<Vector<String>>();
            jTable2.setModel(new javax.swing.table.DefaultTableModel(data,cols));
//            while (table.getRowCount() < 0)
//                table.removeRow(0);
            
            for(int i = 0; i < allRequests.size(); i++)
            {
                Vector<String> oneRequest = new Vector<String>();
                oneRequest.add("" + allRequests.get(i).getCustomerID());
                oneRequest.add(allRequests.get(i).getSKU());
                GregorianCalendar date = allRequests.get(i).getRequestDate();
                String dateString = "" + date.get(date.YEAR) + "-" + date.get(date.MONTH) + "-" + date.get(date.DATE);
                oneRequest.add(dateString);
                data.add(oneRequest);
            }
            
            
            jTable2.setModel(new javax.swing.table.DefaultTableModel(data,cols));
            //table.addRow(cols);
        }
        catch(SQLException e)
        {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Database Data Error", 0);
        }
        catch(ClassNotFoundException e)
        {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Database Driver Error", 0);
        }
        table.fireTableStructureChanged();
    }//GEN-LAST:event_getAllRequests

    private void generateMonthlyReport(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateMonthlyReport
        GregorianCalendar today = new GregorianCalendar();
        GregorianCalendar before = new GregorianCalendar(today.YEAR, today.MONTH - 1, today.DATE);
        String path = jTextField2.getText();
        try
        {
            SaleReporter reporter = new SaleReporter();
            reporter.generateReport(before, today, path);
            javax.swing.JOptionPane.showMessageDialog(this, "Sale report successfully" +
                    " generated", "Successful", 1);
        }
        catch(SQLException e)
        {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Database Error.", 0);
        }
        catch(IOException e)
        {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Destination path is bad.", 0);
        }
        catch(ClassNotFoundException e)
        {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Database Driver Problem", 0);
        }
    }//GEN-LAST:event_generateMonthlyReport

    private void generateAnnualReport(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateAnnualReport
        GregorianCalendar today = new GregorianCalendar();
        GregorianCalendar before = new GregorianCalendar(today.YEAR - 1, today.MONTH, today.DATE);
        String path = jTextField2.getText();
        try
        {
            SaleReporter reporter = new SaleReporter();
            reporter.generateReport(before, today, path);
            javax.swing.JOptionPane.showMessageDialog(this, "Sale report successfully" +
                    " generated", "Successful", 1);
        }
        catch(SQLException e)
        {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Database Error.", 0);
        }
        catch(IOException e)
        {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Destination path is bad.", 0);
        }
        catch(ClassNotFoundException e)
        {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Database Driver Problem", 0);
        }
    }//GEN-LAST:event_generateAnnualReport

    private void clearAllRequest(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllRequest
        try
        {
            Object[] options = {"YES","NO"};
            int choice = javax.swing.JOptionPane.showOptionDialog(this, "Are you sure you "
                    + "want to clear ALL request?",
                    "Confirm",
                    javax.swing.JOptionPane.YES_NO_CANCEL_OPTION,
                    javax.swing.JOptionPane.QUESTION_MESSAGE,
                    null,
                    options,
                    options[1]);
            if(choice == 0)
            {
                MovieManagement movieMan = new MovieManagement();
                movieMan.clearAllRequests();
                javax.swing.JOptionPane.showMessageDialog(this, "All request hav"
                        + "e been removed.", "Romved Requests", 1);
            }
            jTable2 = null;
            getAllRequests(evt);
        }
        catch(SQLException e)
        {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Database Error.", 0);
        }
        catch(ClassNotFoundException e)
        {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Database Driver Problem", 0);
        }
    }//GEN-LAST:event_clearAllRequest

    private void removeRequest(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeRequest
        int[] lines = jTable2.getSelectedRows();
        if(lines.length == 0)
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select at l"
                    + "east one row from the table", "Selection Problem",2);
        }
        else
        {
            Object[] options = {"YES","NO"};
            int choice = javax.swing.JOptionPane.showOptionDialog(this, "Are you sure you "
                        + "want to remove the selected request?",
                        "Confirm",
                        javax.swing.JOptionPane.YES_NO_CANCEL_OPTION,
                        javax.swing.JOptionPane.QUESTION_MESSAGE,
                        null,
                        options,
                        options[1]);
            if(choice == 0)            
            {
                try
                {
                    MovieManagement movieMan = new MovieManagement();
                    for(int i = 0 ; i < lines.length; i++)
                    {
                        String SKU = (String)jTable2.getValueAt(i, 0);
                        movieMan.removeRequest(SKU);
                    }
                }
                catch(SQLException e)
                {
                    javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(),
                            "Database Error.", 0);
                }
                catch(ClassNotFoundException e)
                {
                    javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(),
                            "Database Driver Problem", 0);
                }
            }
            getAllRequests(evt);
        }
    }//GEN-LAST:event_removeRequest


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel reportPanel;
    private javax.swing.JPanel reportPanel1;
    // End of variables declaration//GEN-END:variables

}
