/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StockItemsDialog.java
 *
 * Created on 13-Apr-2011, 11:43:56 AM
 */

package ui;

/**
 *
 * @author kpoirier00
 */
public class StockItemsDialog extends javax.swing.JDialog {

    /** Creates new form StockItemsDialog */
    public StockItemsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        skuStockItemLabel = new javax.swing.JLabel();
        saleRentalStockItemLabel = new javax.swing.JLabel();
        QuantityStockItemLabel = new javax.swing.JLabel();
        skuStockItemTextField = new javax.swing.JTextField();
        quantityStockItemSpinner = new javax.swing.JSpinner();
        saleStockItemRadioButton = new javax.swing.JRadioButton();
        rentalStockItemRadioButton = new javax.swing.JRadioButton();
        addVideoStockItemButton = new javax.swing.JButton();
        cancelStockItemButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        skuStockItemLabel.setText("SKU");

        saleRentalStockItemLabel.setText("Sale/Rental");

        QuantityStockItemLabel.setText("Stock Quantity");

        buttonGroup1.add(saleStockItemRadioButton);
        saleStockItemRadioButton.setText("Sale");

        buttonGroup1.add(rentalStockItemRadioButton);
        rentalStockItemRadioButton.setText("Rental");
        rentalStockItemRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentalStockItemRadioButtonActionPerformed(evt);
            }
        });

        addVideoStockItemButton.setText("Add Video");

        cancelStockItemButton.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(skuStockItemLabel)
                            .addComponent(saleRentalStockItemLabel)
                            .addComponent(QuantityStockItemLabel))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(skuStockItemTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(quantityStockItemSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saleStockItemRadioButton)
                                .addGap(43, 43, 43)
                                .addComponent(rentalStockItemRadioButton)))
                        .addContainerGap(88, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addVideoStockItemButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancelStockItemButton)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(skuStockItemLabel)
                    .addComponent(skuStockItemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saleRentalStockItemLabel)
                    .addComponent(saleStockItemRadioButton)
                    .addComponent(rentalStockItemRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuantityStockItemLabel)
                    .addComponent(quantityStockItemSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelStockItemButton)
                    .addComponent(addVideoStockItemButton))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rentalStockItemRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentalStockItemRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentalStockItemRadioButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StockItemsDialog dialog = new StockItemsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel QuantityStockItemLabel;
    private javax.swing.JButton addVideoStockItemButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelStockItemButton;
    private javax.swing.JSpinner quantityStockItemSpinner;
    private javax.swing.JRadioButton rentalStockItemRadioButton;
    private javax.swing.JLabel saleRentalStockItemLabel;
    private javax.swing.JRadioButton saleStockItemRadioButton;
    private javax.swing.JLabel skuStockItemLabel;
    private javax.swing.JTextField skuStockItemTextField;
    // End of variables declaration//GEN-END:variables

}
